apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secretName }}
  labels:
    {{- include "eap-demo.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
stringData:
  host: {{ .Values.database.host | quote }}
  port: {{ .Values.database.port | quote }}
  database: {{ .Values.database.name | quote }}
  username: {{ .Values.database.username | quote }}
  password: {{ .Values.database.password | quote }}
