# KUBE_PING requires permission to list pods in the namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "eap-demo.fullname" . }}-kube-ping
  labels:
    {{- include "eap-demo.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: {{ include "eap-demo.fullname" . }}
