{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "eap-demo.fullname" . }}
  labels:
    {{- include "eap-demo.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "eap-demo.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: admin
      path: {{ .Values.monitoring.path }}
      interval: {{ .Values.monitoring.interval }}
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
{{- end }}
